version: '3.1'

services:

  db:
    image: postgres
    container_name: pg_starter
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - 5432:5432
  redis:
    image: redis
    container_name: redis_statrter
    ports:
    - 6379:6379